[package]
name = "discloud-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
colored = "2.0.0"
directories = "4.0.1"
reqwest = { version = "0.11.11", features = ["blocking", "json"] }
sentry = "0.27.0"
spinners = "4.1.0"
